# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
  - main
  - test1

pool: new

steps:
- task: TerraformInstaller@1
  displayName: TerraformInstall
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\new'
    backendServiceArm: 'Azure subscription 1(6eb6ee21-8952-4718-9243-5a0101ee200e)'
    backendAzureRmResourceGroupName: 'vipintest'
    backendAzureRmStorageAccountName: 'vipinst123'
    backendAzureRmContainerName: 'stvipin123'
    backendAzureRmKey: 'terrafrom.tfstate'

- task: TerraformTask@5
  displayName: terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)\new'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)\new'
      environmentServiceNameAzureRM: 'Test'
      environmentAzureRmOverrideSubscriptionID: '6eb6ee21-8952-4718-9243-5a0101ee200e'

